// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSong(arg1) {
  return window['go']['main']['App']['AddSong'](arg1);
}

export function DeleteSong(arg1) {
  return window['go']['main']['App']['DeleteSong'](arg1);
}

export function GetAllSongs() {
  return window['go']['main']['App']['GetAllSongs']();
}

export function RandomPick(arg1) {
  return window['go']['main']['App']['RandomPick'](arg1);
}

export function ToggleBlacklist(arg1) {
  return window['go']['main']['App']['ToggleBlacklist'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function UpdateSong(arg1) {
  return window['go']['main']['App']['UpdateSong'](arg1);
}
