// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddSong(arg1:models.Song):Promise<void>;

export function DeleteSong(arg1:number):Promise<void>;

export function GetAllSongs():Promise<Array<models.Song>>;

export function RandomPick(arg1:models.RandomOptions):Promise<Array<models.Song>>;

export function ToggleBlacklist(arg1:number):Promise<void>;

export function ToggleFavorite(arg1:number):Promise<void>;

export function UpdateSong(arg1:models.Song):Promise<void>;
